### PR TITLE
Sort `#include`'s in `clang-format`

### PR DESCRIPTION
**Pull request by aloisklink**
This PR activates the `#include` sorting part of `clang-format`, since in C and C++, **compiling behaviour might change when `#include` order is changed** (e.g. `cmocka.h` must be `#include`-d after `<stdint.h>`

### CODE REVIEW

**Comment by aloisklink** [comment]
Hi @mereacre, sorting the `#include's` in C/C++ can actually change behaviour, since some ~amazing~ libraries require `#include`s to be includes in a certain order.

I know you've previously said that you want to take a while to test this code, so it's fine to leave this open for a while if you want.

**Comment by aloisklink** [comment]
Hey @mereacre, I've rebased this branch onto https://github.com/nqminds/EDGESec/commit/2c39ff34b05c8666bc0a4f87c8c690fe55967555 to fix the merge conflicts.

It looks like it compiles successfully locally and tests pass, so it's probably okay.

**Comment by aloisklink** [comment]
Hi @mereacre, I've rebased this branch on the current `main` contents (e.g. e7b6fee9048bfab17c789c9d1f798a50acde1c5d).

The only issue I found was that `list.h` from hostapd was missing a `#include <stddef.h>`, so I've fixed that in https://github.com/nqminds/edgesec/pull/116/commits/624b318b914215eb97a4b6db2429122da124f8c4

Let me know if you dislike the order of the include headers, because we can easily change it using the settings in https://clang.llvm.org/docs/ClangFormatStyleOptions.html

**Review by mereacre — APPROVED** [review]

**Comment by aloisklink** [comment]
Just to let you know @mereacre, you may need to run a `rm -r build/` before rebuilding `edgesec`, in order to force CMake to re-patch the `eloop` code.

**Pull request merged**
