### PR TITLE
Update control

### PR DESCRIPTION
**Pull request by mereacre**
Change the minimal version of cmake to 3.19.0 to allow presets.

### CODE REVIEW

**Comment by mereacre** [comment]
The issue that I have is that we are using mainly presets. I don't expect other developers not to use presets and version 3.16 is pretty much useless for us.

I know snap has a more recent version of cmake. Can we integrate with snap?

**Comment by aloisklink** [comment]
> The issue that I have is that we are using mainly presets. I don't expect other developers not to use presets and version 3.16 is pretty much useless for us.

True, true, but on the other side, the Debian build preset is pretty different from the rest of the other CMake development presets, so it's not too much trouble manually specify the `-DMY_VAR=VALUE` for it (I believe we need to do the same thing for OpenWRT buildroot).

> I know snap has a more recent version of cmake. Can we integrate with snap?

`snap` is great for applications, but it's pretty awful to use for automated builds. The entire point of the Debian build is that it uses the Debian system to build, so that we can make our own https://help.launchpad.net/Packaging/PPA or even add our package to Debian/Ubuntu once it gets more stable.

Plus, I don't even know if `snap` supports `armhf` (e.g. old raspberry pis/Turris Omnia), since Ubuntu doesn't support them. However, the Debian project still supports them.

Plus, if we want to publish `edgesec` as a `snap`, we'd have to ask for Ubuntu's permission, there's no way to self-host a snap, as far as I'm aware.

**Comment by mereacre** [comment]
@aloisklink What's the decision on this PR? Do we close it and later on we add the snap integration?

**Comment by aloisklink** [comment]
> Do we close it and later on we add the snap integration?

That's my gut feeling. But I'll be honest, I still think we should keep deb integration too, for Debian/light-weight Ubuntu distros.

It would also be nice to set up an edgesec PPA too so that we can have a super easy way to install edgesec on Debian/Ubuntu (and do automatic updates).

**Pull request closed without merging**
